receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlp/elastic:
    endpoint: "${env:ELASTIC_APM_SERVER_ENDPOINT}"
    headers:
      Authorization: "Bearer ${env:ELASTIC_APM_SECRET_TOKEN}"

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug, otlp/elastic]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug, otlp/elastic]
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug, otlp/elastic]
