receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlphttp: # seq
    endpoint: http://seq:5341/ingest/otlp
  otlp: # jaeger
    endpoint: jaeger:4317
    tls:
      insecure: true
  zipkin: # zipkin
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp, zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]
