receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlp/elastic:
    endpoint: "http://apm-server:8200"
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/elastic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/elastic]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/elastic]
